export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_MEN_PRODUCT_SUCCESS = "GET_MEN_PRODUCT_SUCCESS";
export const GET_WOMEN_PRODUCT_SUCCESS = "GET_WOMEN_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
