export const PRODUCT_REQUEST = "POST_PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "POST_PRODUCT_FAILURE";

//making post request
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
//making get request
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

//making patch request
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

//ORDERS
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const PATCH_ORDER_SUCCESS = "PATCH_ORDER_SUCCESS";
